version: '3.8'

networks:
  ndu-tv-net:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: ndutv-redis
    ports:
      - '6378:6379'
    networks:
      - ndu-tv-net
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: ndu-tv-server
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ndu-tv-net
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
