[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build:prod"

[build.env]
NIXPACKS_NO_CACHE = "1"
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"

[deploy]
startCommand = "pnpm run start:prod"

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=900"